# Generated by Django 3.0.6 on 2020-05-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateField(default=0),
            preserve_default=False,
        ),
    ]
