# Generated by Django 3.0.6 on 2020-05-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_remove_myblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
