# Generated by Django 3.0.6 on 2020-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_myblog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myblog',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
