# Generated by Django 3.0.6 on 2020-05-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
